[workspace]
resolver = "2"
members = [
    "core",
    "sources/http",
    "sources/spotify",
    "sources/soundcloud",
    "sources/soulseek",
    "sources/bpm",
    "sources/bpm-deezer",
    "sources/bpm-getsongbpm",
    "sources/genre-embed",
    "sources/cached",
    "sources/waveform",
    "player",
    "ui",
    "app",
]

[workspace.package]
version = "0.5.4"
authors = ["medley"]
edition = "2024"
license = "MIT"
repository = "https://github.com/aurabirb/greyball"

[workspace.lints.clippy]
enum_glob_use = "warn"

[profile.release]
lto = true
codegen-units = 1
