[package]
name = "ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "ui"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
core = { path = "../core" }
cursive = { version = "0.21", default-features = false, features = ["crossterm-backend"] }
fuzzy-matcher = "0.3"
log = "0.4"
unicode-width = "0.2"
